In [1]:
import pymongo
cliente=pymongo.MongoClient()
db=cliente.nueva_db

In [2]:
db

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'nueva_db')

In [3]:
print (cliente.list_database_names())

['admin', 'config', 'local']

In [4]:
colec=db.n_colec

In [5]:
print (db.list_collection_names())

[]

In [12]:
import pandas as pd
from pandas.io.json import json_normalize

In [9]:
companies = pd.read_json('../mongo/companies.json',lines=True)

In [26]:
oficinas = companies['offices'][0]
oficinas

[{'description': '',
  'address1': '710 - 2nd Avenue',
  'address2': 'Suite 1100',
  'zip_code': '98104',
  'city': 'Seattle',
  'state_code': 'WA',
  'country_code': 'USA',
  'latitude': 47.603122,
  'longitude': -122.333253},
 {'description': '',
  'address1': '270 Lafayette Street',
  'address2': 'Suite 505',
  'zip_code': '10012',
  'city': 'New York',
  'state_code': 'NY',
  'country_code': 'USA',
  'latitude': 40.7237306,
  'longitude': -73.9964312}]

In [27]:
df_oficinas = json_normalize(oficinas)
df_oficinas

,description,address1,address2,zip_code,city,state_code,country_code,latitude,longitude
0,,710 - 2nd Avenue,Suite 1100,98104,Seattle,WA,USA,47.603122,-122.333253
1,,270 Lafayette Street,Suite 505,10012,New York,NY,USA,40.723731,-73.996431

In [29]:
def obtenerUbicacionOficinas(lista):
    return json_normalize(lista)

In [31]:
for i in range(1,len(companies['offices'])):
    df_oficinas = pd.concat([df_oficinas, obtenerUbicacionOficinas(companies['offices'][i])])

KeyboardInterrupt:

In [32]:
len(df_oficinas)

13715

In [34]:
df_oficinas.to_csv('offices.csv')

In [35]:
companies

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,offices,milestones,video_embeds,screenshots,external_links,partners,deadpooled_month,deadpooled_day,deadpooled_url,ipo
0,{'$oid': '52cdef7c4bab8bd675297d8a'},Wetpaint,abc2,http://www.crunchbase.com/company/wetpaint,http://wetpaint-inc.com,http://digitalquarters.net/,http://digitalquarters.net/feed/,BachelrWetpaint,web,47.0,...,"[{'description': '', 'address1': '710 - 2nd Av...","[{'id': 5869, 'description': 'Wetpaint named i...",[],"[{'available_sizes': [[[150, 86], 'assets/imag...",[{'external_url': 'http://www.geekwire.com/201...,[],NaN,NaN,NaN,NaN
1,{'$oid': '52cdef7c4bab8bd675297d8b'},AdventNet,abc3,http://www.crunchbase.com/company/adventnet,http://adventnet.com,,,manageengine,enterprise,600.0,...,"[{'description': 'Headquarters', 'address1': '...",[],[],"[{'available_sizes': [[[150, 94], 'assets/imag...",[],[],NaN,NaN,NaN,NaN
2,{'$oid': '52cdef7c4bab8bd675297d8c'},Zoho,abc4,http://www.crunchbase.com/company/zoho,http://zoho.com,http://blogs.zoho.com/,http://blogs.zoho.com/feed,zoho,software,1600.0,...,"[{'description': 'Headquarters', 'address1': '...","[{'id': 388, 'description': 'Zoho Reaches 2 Mi...","[{'embed_code': '<object width=""430"" height=""2...",[],[{'external_url': 'http://www.online-tech-tips...,[],NaN,NaN,NaN,NaN
3,{'$oid': '52cdef7c4bab8bd675297d8d'},Digg,digg,http://www.crunchbase.com/company/digg,http://www.digg.com,http://blog.digg.com/,http://blog.digg.com/?feed=rss2,digg,news,60.0,...,"[{'description': None, 'address1': '135 Missis...","[{'id': 9588, 'description': 'Another Digg Exe...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[117, 150], 'assets/ima...",[{'external_url': 'http://www.sociableblog.com...,[],NaN,NaN,None,None
4,{'$oid': '52cdef7c4bab8bd675297d8e'},Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,...,"[{'description': 'Headquarters', 'address1': '...","[{'id': 108, 'description': 'Facebook adds com...",[],"[{'available_sizes': [[[150, 68], 'assets/imag...",[{'external_url': 'http://latimesblogs.latimes...,[],NaN,NaN,,"{'valuation_amount': 104000000000, 'valuation_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18796,{'$oid': '52cdef7f4bab8bd67529c6f6'},Adhunk,adhunk,http://www.crunchbase.com/company/adhunk,http://www.adhunk.com,http://blog.adhunk.com,http://blog.adhunk.com/feed,,advertising,3.0,...,"[{'description': 'Indian Office', 'address1': ...",[],[],[],[{'external_url': 'http://www.hubpages.in/inte...,[],NaN,NaN,None,None
18797,{'$oid': '52cdef7f4bab8bd67529c6f7'},AfterLogic,afterlogic,http://www.crunchbase.com/company/afterlogic,http://www.afterlogic.com,,,afterlogic,software,NaN,...,"[{'description': 'Livingston', 'address1': 'P....",[],[],"[{'available_sizes': [[[150, 137], 'assets/ima...",[],[],NaN,NaN,None,None
18798,{'$oid': '52cdef7f4bab8bd67529c6f8'},goBookmaker,gobookmaker,http://www.crunchbase.com/company/gobookmaker,http://www.gobookmaker.com,http://blog.gobookmaker.com,,gobookmaker,web,NaN,...,[],[],[],"[{'available_sizes': [[[150, 80], 'assets/imag...",[],[],NaN,NaN,None,None
18799,{'$oid': '52cdef7f4bab8bd67529c6f9'},EnteGreat Solutions,entegreat-solutions,http://www.crunchbase.com/company/entegreat-so...,,,,,software,NaN,...,"[{'description': '', 'address1': '', 'address2...",[],[],[],[],[],NaN,NaN,None,None
18800,{'$oid': '52cdef7f4bab8bd67529c6fa'},EnteGreat,entegreat,http://www.crunchbase.com/company/entegreat,http://www.entegreat.com,,,,enterprise,NaN,...,"[{'description': '', 'address1': '1900 Interna...",[],[],[],[],[],NaN,NaN,None,None